/* BESMA collection monitor UI 1.4.1. Existing login, scoped government preview. */
const API='https://api.besma.co.kr';
function previewSite(){return ['SITE_STAFF','SITE_MANAGER'].includes(localStorage.getItem('besma_test_persona'))?localStorage.getItem('besma_test_site_context_id')||'':'';}
function workspaceKey(){return (localStorage.getItem('besma_token')||'')+'|'+(localStorage.getItem('besma_test_persona')||'')+'|'+previewSite();}
let token='',ctx=null,contextPending=false,loading=false,data=null,root=null,currentMonth=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit'}).format(new Date()),team='전체',channel='BESMA',search='',doc='전체',onlyMissing=false,priorityOnly=true;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
async function api(path,options={}){const session=localStorage.getItem('besma_token');if(!session)throw Error('로그인이 필요합니다.');const key=workspaceKey(),preview=previewSite();if(preview){if(!['GET','HEAD','OPTIONS'].includes((options.method||'GET').toUpperCase()))throw Error('관점 전환에서는 조회만 가능합니다.');path+=(path.includes('?')?'&':'?')+'preview_site_id='+encodeURIComponent(preview);}const r=await fetch(API+path,{...options,headers:{Authorization:'Bearer '+session,...options.headers},cache:'no-store'});if(session!==localStorage.getItem('besma_token')||key!==workspaceKey())throw Error('로그인 계정 또는 관점이 변경됐습니다.');if(!r.ok)throw Error(r.status===403?'이 작업의 권한을 확인해 주세요.':r.status===401?'로그인 상태를 확인해 주세요.':'자료를 확인하지 못했습니다. 다시 시도해 주세요.');return r.json();}
function button(text,fn){const e=el('button',text);e.type='button';e.onclick=fn;return e;}
function select(label,values,value,onchange){const wrap=el('label',label);const s=el('select');for(const [v,t] of values){const o=el('option',t);o.value=v;s.append(o);}s.value=value;s.onchange=()=>onchange(s.value);wrap.append(s);return wrap;}
function clear(){root?.remove();root=null;data=null;ctx=null;document.querySelectorAll('[data-collection-hidden]').forEach(e=>{e.hidden=false;delete e.dataset.collectionHidden;});}
function hide(e){e.hidden=true;e.dataset.collectionHidden='true';}
function rates(cells){const n=cells.reduce((a,c)=>a+c.expected,0),d=cells.reduce((a,c)=>a+c.received,0);return {n,d,rate:n&&cells.every(c=>c.known)?(100*d/n).toFixed(1)+'%':'확인 필요'};}
async function load(silent=false){if(!root||loading)return;loading=true;const previous=root.querySelector('.cm-matrix-wrap');const scroll=silent&&previous?{top:previous.scrollTop,left:previous.scrollLeft}:null;if(!silent)root.replaceChildren(el('p','취합현황을 불러오고 있습니다.'));try{data=await api('/collection-monitor/overview?month='+currentMonth+'&scope='+(channel==='BESMA'?'government':'other')+'&priority_only='+priorityOnly);if(root){render();const next=root.querySelector('.cm-matrix-wrap');if(scroll&&next){next.scrollTop=scroll.top;next.scrollLeft=scroll.left;}}}catch(e){if(root)root.replaceChildren(el('p',e.message),button('다시 시도',load));}finally{loading=false;}}
function render(){if(!root||!data)return;root.replaceChildren();const head=el('header');head.append(el('h1','문서취합현황'),el('p','관급은 BESMA 제출자료, 그 외 현장은 네이버웍스에서 취합한 NAS 자료를 확인합니다.'));root.append(head);const scopes=el('div',undefined,'cm-tools');for(const [value,label] of [['BESMA','관급공사'],['NAVERWORKS','기타 현장']]){const b=button(label,()=>{channel=value;team='전체';doc='전체';onlyMissing=false;load();});b.setAttribute('aria-pressed',String(channel===value));scopes.append(b);}if(channel==='BESMA')scopes.append(button(priorityOnly?'전체 서류 보기':'우선 서류만 보기',()=>{priorityOnly=!priorityOnly;doc='전체';load();}));root.append(scopes);
const tools=el('div',undefined,'cm-tools');const month=el('input');month.type='month';month.value=currentMonth;month.setAttribute('aria-label','취합월');month.onchange=()=>{currentMonth=month.value;load();};tools.append(month,select('팀', ['전체','1팀','2팀','3팀','4팀','5팀','6팀','관급'].map(x=>[x,x]),team,x=>{team=x;render();}),select('필수 문서',[['전체','전체'],...data.documents.filter(d=>d.code.startsWith('NAS_')).map(d=>['CAT_'+d.category,d.title+' (전 현장)']),...data.documents.filter(d=>d.code.startsWith('GOV_')).map(d=>[d.code,'관급 · '+d.title])],doc,x=>{doc=x;render();}));const find=el('input');find.placeholder='현장명 / 현장코드';find.value=search;find.setAttribute('aria-label','현장 검색');find.oninput=()=>{search=find.value;drawResults();};tools.append(find,button('새로고침',load));
const check=(text,value,fn)=>{const l=el('label');const i=el('input');i.type='checkbox';i.checked=value;i.onchange=()=>fn(i.checked);l.append(i,document.createTextNode(text));return l;};if(channel!=='BESMA')tools.append(check('누락만 보기',onlyMissing,x=>{onlyMissing=x;render();}));if(ctx.can_manage)tools.append(button('취합현황 보고서 다운로드',downloadReport));if(ctx.can_manage&&channel==='BESMA')tools.append(button('NAS에 저장',saveNas));root.append(tools);
const note=el('p',undefined,'cm-note');note.textContent=data.scan?'NAS 확인: '+new Date(data.scan.observed_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' · 현장/기간 확인 필요 '+data.unmapped_count+'개':'NAS 취합실적을 아직 연결하지 않았습니다.';if(channel!=='BESMA')root.append(note);
if(ctx.can_manage&&channel!=='BESMA')root.append(button('현장·기간 확인 필요 자료 ('+data.unmapped_count+')',unmapped));
const results=el('div');results.id='cm-results';root.append(results);drawResults();
const legacy=button('관급 제출·검토 상세 화면',()=>{const old=root.parentElement.querySelector('.hq-doc-grid');if(old){old.hidden=!old.hidden;if(!old.hidden)delete old.dataset.collectionHidden;old.scrollIntoView({behavior:'smooth'});}});root.append(legacy);}
function matches(c){return doc==='전체'||c.code===doc||'CAT_'+c.category===doc;}
function filtered(){return data.sites.filter(s=>s.active&&(team==='전체'||s.team===team)&&(channel==='전체'||s.channel===channel)&&(!search||(s.site_name+' '+s.site_code).toLowerCase().includes(search.toLowerCase()))&&(!onlyMissing||s.cells.filter(matches).some(c=>c.expected>c.received)));}
function periodLabel(p){return p==='once'?'착공':p.includes('-W')?p.split('-W')[1]+'주차':p;}
const statusLabels={NOT_REQUIRED:'대상 없음',NOT_SUBMITTED:'미제출',SUBMITTED:'제출',RESUBMITTED:'재제출',UNDER_REVIEW:'검토중',IN_REVIEW:'검토중',APPROVED:'승인',REJECTED:'반려',UNCONFIRMED:'미확인'};
function appendContacts(node,site){node.append(el('small',(site.contact_role||'담당자')+': '+(site.contact_name||'미등록')),el('small','연락처: '+(site.contact_phone|| (site.contact_phone_needs_confirmation?'확인 필요':'미등록'))));for(const contact of site.additional_contacts||[])node.append(el('small',contact.role+': '+(contact.name||'미등록')+' · '+(contact.phone||'연락처 미등록')));}
function drawResults(){const results=root?.querySelector('#cm-results');if(!results)return;results.replaceChildren();const rows=filtered();
if(channel!=='BESMA'){drawOtherResults(results,rows);return;}
results.append(el('h2','현장별 서류 제출 현황'),el('p','현장 '+rows.length+'개 · 서류별 상태를 누르면 제출자료와 검토 내용을 확인합니다.','cm-note'));
const defs=data.documents.filter(d=>doc==='전체'||d.code===doc);const wrap=el('div',undefined,'cm-table-wrap cm-matrix-wrap');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','현장별 서류 제출 현황');const table=el('table',undefined,'cm-matrix');const head=el('thead');
const groups=el('tr');const siteHead=el('th','현장명 / 담당자 · 연락처');siteHead.rowSpan=2;groups.append(siteHead);
const grouped=(data.groups||[{id:'MONTHLY',label:'월간',order:0},{id:'WEEKLY',label:'주간',order:1},{id:'EVENT',label:'착공시',order:2}]).slice().sort((a,b)=>a.order-b.order).map(group=>({...group,columns:defs.filter(d=>(d.group_id||(['EVENT','ADHOC'].includes(d.frequency)?'EVENT':d.frequency==='WEEKLY'?'WEEKLY':'MONTHLY'))===group.id)}));
for(const group of grouped){if(group.columns.length){const th=el('th',group.label);th.colSpan=group.columns.length;groups.append(th);}}
const columns=el('tr');const ordered=grouped.flatMap(group=>group.columns);for(const def of ordered){const th=el('th',def.title);const parts=({'산업안전보건관리비':['산업안전보건','관리비'],'안전보건관리책임자 지정서':['안전보건관리','책임자 지정서']})[def.title];if(parts){th.replaceChildren(document.createTextNode(parts[0]),el('wbr'),document.createTextNode(parts[1]));}columns.append(th);}head.append(groups,columns);table.append(head);
const body=el('tbody');for(const site of rows){const row=el('tr');const name=el('td');name.append(button(site.site_name,()=>detail(site)),el('small',site.site_code+' · '+site.team),el('small',site.contact_name?'':''));appendContacts(name,site);if(ctx.can_manage){const contact=button('소통',()=>window.dispatchEvent(new CustomEvent('besma-government-contact',{detail:{site_id:site.id}})));contact.className='cm-site-contact';name.append(contact);}row.append(name);
for(const def of ordered){const td=el('td');td.dataset.document=def.title;const cell=site.cells.find(c=>c.code===def.code);if(!cell){td.append(el('span','대상 없음'));row.append(td);continue;}
const periods=cell.periods?.length?cell.periods:[{period:cell.frequency==='WEEKLY'?'':cell.frequency==='EVENT'?'once':currentMonth,status:cell.status,instance_id:cell.latest_instance_id}];for(const period of periods){const stack=el('div',undefined,'cm-period-status');stack.append(el('small',periodLabel(period.period)));const status=button(statusLabels[period.status]||'미제출',()=>{if(period.instance_id)location.assign('/hq-safe/document-instances/'+period.instance_id);else detail(site,cell.code);});status.className='cm-status cm-status-'+period.status.toLowerCase();status.title=period.file_name||'제출자료 및 이력';stack.append(status);td.append(stack);}row.append(td);}body.append(row);}
if(!rows.length){const row=el('tr');const td=el('td','조건에 맞는 현장이 없습니다.');td.colSpan=ordered.length+1;row.append(td);body.append(row);}table.append(body);wrap.append(table);results.append(wrap);}
function drawOtherResults(results,rows){const cells=rows.flatMap(s=>s.cells.filter(matches));const r=rates(cells);const summary=el('div',undefined,'cm-summary');summary.append(el('strong','취합률 '+r.rate),el('span',r.d+' / '+r.n+' 필수기간'),el('span','현장 '+rows.length+'곳'));results.append(summary);const wrap=el('div',undefined,'cm-table-wrap');const table=el('table');const head=el('tr');['현장 / 담당자 · 연락처','팀','취합률','누락 / 확인 필요'].forEach(t=>head.append(el('th',t)));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');for(const s of rows){const row=el('tr');const name=el('td');name.append(el('strong',s.site_name),el('small',s.site_code),el('small','담당자: '+(s.contact_name||'미등록')+' · 연락처: '+(s.contact_phone||'미등록')));const cs=s.cells.filter(matches);const rate=rates(cs);const missing=cs.filter(c=>c.expected>c.received);const last=el('td');last.append(button(missing.map(c=>c.title).join(', ')||'취합 확인',()=>detail(s)));row.append(name,el('td',s.team),el('td',rate.rate+' · '+rate.d+'/'+rate.n),last);body.append(row);}table.append(body);wrap.append(table);results.append(wrap);}
function modal(title){const d=el('dialog');d.className='cm-dialog';d.append(el('h2',title),button('닫기',()=>d.close()));d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return d;}
function detail(s,code=null){const d=modal(s.site_name);for(const c of s.cells.filter(c=>matches(c)&&(!code||c.code===code))){const row=el('article');row.append(el('strong',c.title),el('p',!c.expected?'기간 외':c.received+'/'+c.expected+' · '+(c.received===c.expected?'취합 확인':s.channel==='BESMA'?'미업로드: '+c.missing_periods.join(', '):c.known?'확인된 자료 없음: '+c.missing_periods.join(', '):'NAS 확인 필요')));if(c.latest_instance_id){const a=el('a','제출자료·검토 보기');a.href='/hq-safe/document-instances/'+c.latest_instance_id;row.append(a);}d.append(row);}}
async function unmapped(){const d=modal('현장·기간 확인 필요 자료');try{const response=await api('/collection-monitor/unmapped?month='+currentMonth);if(!response.items.length)d.append(el('p','확인 대기 자료가 없습니다.'));for(const item of response.items){const row=el('article');row.append(el('strong',item.filename),el('p',item.relative_path));const sites=select('현장',[['','현장을 선택하세요'],...data.sites.map(s=>[String(s.id),s.team+' · '+s.site_name])],String(item.site_id||''),()=>{});const period=el('input');period.value=item.period||currentMonth+(item.category==='nonconformity'?'-W1':'');period.setAttribute('aria-label','제출기간');const open=button('파일 확인',async()=>{try{const session=localStorage.getItem('besma_token');const r=await fetch(API+'/collection-monitor/copies/'+item.id+'/content',{headers:{Authorization:'Bearer '+session},cache:'no-store'});if(!r.ok)throw Error('파일 열람 권한을 확인해 주세요.');const url=URL.createObjectURL(await r.blob());const a=el('a');a.href=url;a.download=item.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){row.append(el('p',e.message));}});row.append(sites,period,open,button('접수 현장·기간 확인',async()=>{try{if(!sites.querySelector('select').value)throw Error('접수 현장을 선택해 주세요.');await api('/collection-monitor/copies/'+item.id+'/classify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site_id:Number(sites.querySelector('select').value),period:period.value})});row.remove();load();}catch(e){row.append(el('p',e.message));}}));d.append(row);}}catch(e){d.append(el('p',e.message));}}
async function reconcile(){const session=localStorage.getItem('besma_token')||'',key=workspaceKey();if(key!==token){token=key;clear();}if(!session)return;if(!ctx){if(contextPending)return;contextPending=true;try{ctx=await api('/collection-monitor/context');}catch{return;}finally{contextPending=false;}}
document.querySelectorAll('a[href="/hq-safe/artifact-vault"]').forEach(hide);
if(ctx.role==='SITE'&&ctx.channel==='NAVERWORKS')document.querySelectorAll('a[href="/site/documents"],a[href="/site/documents/upload"]').forEach(hide);
if(location.pathname==='/hq-safe/documents'&&ctx.can_read_monitor){const host=document.querySelector('.hq-doc-page');if(host&&!host.querySelector('#collection-monitor')){root=el('section',undefined,'collection-monitor');root.id='collection-monitor';host.prepend(root);const old=host.querySelector('.hq-doc-grid');if(old)hide(old);load();}}
else if(root){root.remove();root=null;}
if(location.pathname==='/site/documents'&&ctx.role==='SITE'){const original=[...document.querySelectorAll('.card-title')].find(e=>e.textContent.includes('현장 문서취합'))?.closest('.card');const host=original?.parentElement;if(host&&ctx.channel==='NAVERWORKS'&&!host.querySelector('.cm-naver-info')){hide(original);const info=el('section',undefined,'cm-naver-info');info.append(el('h1','네이버웍스 문서취합'),el('p','이 현장의 문서는 기존 네이버웍스 드라이브로 제출합니다. 본사에서 전체 현장 취합현황을 확인합니다.'));host.append(info);}else if(host&&ctx.channel==='BESMA'&&!host.querySelector('.cm-gov-info')){const info=el('div','관급 문서 제출 · 본사에서 NAS에 저장 버튼을 누르면 문서 종류별 관급 폴더에 사본을 보관합니다.','cm-gov-info cm-note');original.before(info);}}
}
let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;reconcile();},200);};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});addEventListener('popstate',schedule);addEventListener('storage',schedule);setInterval(schedule,3000);setInterval(()=>{if(root&&document.visibilityState==='visible')load(true);},30000);schedule();

async function response(path,options={}){
 const session=localStorage.getItem('besma_token');if(!session)throw Error('로그인이 필요합니다.');
 const r=await fetch(API+path,{...options,headers:{Authorization:'Bearer '+session,...options.headers},cache:'no-store'});
 if(session!==localStorage.getItem('besma_token'))throw Error('로그인 계정이 변경됐습니다.');
 if(!r.ok)throw Error('다운로드를 완료하지 못했습니다. ('+r.status+')');return r;
}
async function download(path,name){const r=await response(path);const url=URL.createObjectURL(await r.blob());const a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function downloadReport(){const d=modal('취합현황 보고서');try{if(!ctx.can_manage)throw Error('보고서 다운로드는 안전보건실 계정으로 이용해 주세요.');const params=new URLSearchParams({month:currentMonth,scope:channel==='BESMA'?'government':'other',priority_only:String(priorityOnly),q:search,only_missing:String(onlyMissing)});if(team!=='전체')params.set('team',team);if(doc!=='전체')params.set('document_code',doc);await download('/collection-monitor/report.xlsx?'+params,(channel==='BESMA'?'관급공사':'기타현장')+'_문서취합현황_'+currentMonth+'.xlsx');d.append(el('p','현재 선택한 현장과 서류의 취합현황 보고서를 내려받았습니다.'));}catch(e){d.append(el('p',e.message));}}
let nasSaving=false;
async function saveNas(){
 if(nasSaving)return;nasSaving=true;let directory=null,d=null;const month=currentMonth;
 try{
  if(typeof window.showDirectoryPicker==='function')directory=await window.showDirectoryPicker({id:'besma-monthly-collection',mode:'readwrite'});
  d=modal('NAS에 저장');const note=el('p','서버 제출자료를 확인하고 있습니다.');d.append(note);
  if(directory&&directory.name!=='★월간 자료 취합')throw Error('NAS의 ★월간 자료 취합 폴더를 선택해 주세요.');
  const plan=await api('/collection-monitor/nas-export?month='+month);
  if(plan.unavailable_count)throw Error('서버 원본이 없는 문서 '+plan.unavailable_count+'건이 있습니다. 저장을 중단했습니다.');
  if(!plan.items.length){note.textContent='해당 기간에 저장할 관급 제출서류가 없습니다.';return;}
  if(!directory){note.textContent='이 브라우저는 폴더 직접 저장을 지원하지 않습니다. 압축파일을 ★월간 자료 취합 폴더에 풀어 주세요.';d.append(button('NAS 저장용 압축파일 다운로드',()=>download('/collection-monitor/nas-export.zip?month='+month,'관급공사_NAS저장_'+month+'.zip').catch(e=>{note.textContent=e.message;})));return;}
  let saved=0,existing=0;
  for(const item of plan.items){
   const parts=item.relative_path.split('/');if(parts.length<4||parts[1]!=='관급'||parts.some(p=>!p||p==='.'||p==='..'||/[\\:*?"<>|\x00-\x1f]/.test(p)))throw Error('저장 경로를 확인하지 못했습니다.');
   const r=await response('/collection-monitor/nas-files/'+encodeURIComponent(item.key)+'?month='+month);const bytes=await r.arrayBuffer();
   const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');
   if(hash!==item.sha256||bytes.byteLength!==item.size)throw Error('문서 검증에 실패했습니다.');
   let folder=directory;for(const part of parts.slice(0,-1))folder=await folder.getDirectoryHandle(part,{create:true});
   const name=parts.at(-1);let prior=null;try{prior=await folder.getFileHandle(name);}catch(e){if(e.name!=='NotFoundError')throw e;}
   if(prior){const previous=await (await prior.getFile()).arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',previous))).map(b=>b.toString(16).padStart(2,'0')).join('');if(digest!==hash)throw Error('같은 이름의 다른 파일이 있어 저장을 중단했습니다: '+name);existing++;}
   else{const handle=await folder.getFileHandle(name,{create:true});const writer=await handle.createWritable();try{await writer.write(bytes);await writer.close();}catch(e){await writer.abort().catch(()=>{});throw e;}const file=await handle.getFile();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('');if(digest!==hash)throw Error('NAS 저장 검증에 실패했습니다.');saved++;}
   note.textContent='저장 '+saved+'건 · 기존 동일 파일 '+existing+'건 / 전체 '+plan.items.length+'건';
  }
  note.textContent='NAS 저장 완료: 새 사본 '+saved+'건 · 기존 동일 파일 '+existing+'건. 각 문서 분류의 관급 폴더에 저장했습니다.';
 }catch(e){if(e.name!=='AbortError'){if(!d)d=modal('NAS에 저장');d.append(el('p',e.message));}}finally{nasSaving=false;}
}
