from enum import Enum


class Role(str, Enum):
    HQ_SAFE = "HQ_SAFE"
    ACCIDENT_ADMIN = "ACCIDENT_ADMIN"
    SITE = "SITE"
    HQ_OTHER = "HQ_OTHER"
    WORKER = "WORKER"
    HQ_SAFE_ADMIN = "HQ_SAFE_ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"
    SITE_FUNCTIONAL_EVAL = "SITE_FUNCTIONAL_EVAL"
    FUNCTIONAL_EVAL_VIEWER = "FUNCTIONAL_EVAL_VIEWER"
    HQ_BUDGET_ESTIMATE = "HQ_BUDGET_ESTIMATE"
    HQ_OUTSOURCING_PURCHASE = "HQ_OUTSOURCING_PURCHASE"


class FunctionalEvalSafetyAction(str, Enum):
    NONE = "NONE"
    WARNING = "WARNING"
    IMMEDIATE_EXPULSION = "IMMEDIATE_EXPULSION"


class UIType(str, Enum):
    HQ_SAFE = "HQ_SAFE"
    SITE = "SITE"
    HQ_OTHER = "HQ_OTHER"

